package dev.conjure.ai.agents;

import com.google.gson.JsonObject;
import dev.conjure.ai.ProviderFactory;
import dev.conjure.ai.TextModelProvider;

/**
 * Sub-agent that decides the interaction kind for a generated block and, for machine blocks,
 * produces a simple furnace-style recipe.
 *
 * <h2>Interaction kinds</h2>
 * <ul>
 *   <li>{@link Kind#PLAIN} — no interaction; plain placeable block.
 *   <li>{@link Kind#SCRIPT} — right-click runs a Rhino behavior script (generated by
 *       {@link LogicAgent}).
 *   <li>{@link Kind#MACHINE} — right-click opens a 3-slot GUI; the block entity processes
 *       input→output over {@code recipe_ticks} ticks.
 * </ul>
 *
 * <p>The JSON schema returned by the model:
 * <pre>
 * {
 *   "interaction": "plain" | "script" | "machine",
 *   "recipe_input":  "minecraft:wheat",        // only when interaction == "machine"
 *   "recipe_output": "minecraft:bread",         // only when interaction == "machine"
 *   "recipe_ticks":  100                        // only when interaction == "machine"
 * }
 * </pre>
 */
public final class MachineAgent {

    /** The three possible interaction modes for a generated block. */
    public enum Kind { PLAIN, SCRIPT, MACHINE }

    /** Result returned to {@link dev.conjure.gen.pipeline.BlockPipeline}. */
    public record Result(Kind kind, String recipeInput, String recipeOutput, int recipeTicks) {
        /** Convenience constructor for non-machine results. */
        public static Result plain()  { return new Result(Kind.PLAIN,  "", "", 0); }
        public static Result script() { return new Result(Kind.SCRIPT, "", "", 0); }
    }

    private static final String SYSTEM = """
            You decide whether a Minecraft block generated by the Conjure mod should be:
              "plain"   — no interaction (just a decorative/functional placeable block)
              "script"  — right-clicking runs a custom JavaScript behaviour
              "machine" — right-clicking opens a 3-slot crafting machine GUI with a recipe

            For "machine" blocks you must also provide:
              "recipe_input"  — a valid vanilla Minecraft item registry id (e.g. "minecraft:wheat")
              "recipe_output" — a valid vanilla Minecraft item registry id (e.g. "minecraft:bread")
              "recipe_ticks"  — integer number of ticks to process (20 = 1 second, typical 100–200)

            Reply with ONLY a JSON object matching this schema (no prose, no markdown fences):
            {
              "interaction": "plain" | "script" | "machine",
              "recipe_input": "<item id or empty string>",
              "recipe_output": "<item id or empty string>",
              "recipe_ticks": <integer or 0>
            }
            Use common sense: machines should relate to processing or crafting.
            About 30% of blocks should be machines, 30% script-driven, 40% plain.
            """;

    /**
     * Asks the text model what interaction kind best fits {@code prompt}.
     *
     * @param prompt the original user-supplied block description
     * @return a {@link Result} with the chosen kind and optional recipe data
     * @throws Exception if the model call or JSON parse fails
     */
    public Result generate(String prompt) throws Exception {
        TextModelProvider provider = ProviderFactory.text();
        String userMsg = "Decide the interaction kind for this Minecraft block: " + prompt;
        String raw = provider.complete(SYSTEM, userMsg);

        JsonObject obj = JsonHelper.extractAndParse(raw, SYSTEM, provider, userMsg);

        String interaction  = obj.has("interaction")   ? obj.get("interaction").getAsString()   : "plain";
        String recipeInput  = obj.has("recipe_input")  ? obj.get("recipe_input").getAsString()  : "";
        String recipeOutput = obj.has("recipe_output") ? obj.get("recipe_output").getAsString() : "";
        int    recipeTicks  = obj.has("recipe_ticks")  ? obj.get("recipe_ticks").getAsInt()     : 0;

        Kind kind = switch (interaction.toLowerCase().trim()) {
            case "machine" -> Kind.MACHINE;
            case "script"  -> Kind.SCRIPT;
            default        -> Kind.PLAIN;
        };

        // Sanitise recipe fields for non-machine results
        if (kind != Kind.MACHINE) {
            recipeInput  = "";
            recipeOutput = "";
            recipeTicks  = 0;
        }

        return new Result(kind, recipeInput, recipeOutput, recipeTicks);
    }

    public MachineAgent() {}
}
