package dev.conjure.ai.agents;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import dev.conjure.ai.ProviderFactory;
import dev.conjure.ai.TextModelProvider;

import java.util.ArrayList;
import java.util.List;

/**
 * Sub-agent that decides the interaction kind for a generated block and, for workbench blocks,
 * produces a crafting recipe: a flexible list of ingredient items → an output, optionally gated on
 * a fuel item, processed over a number of ticks.
 *
 * <h2>Interaction kinds</h2>
 * <ul>
 *   <li>{@link Kind#PLAIN}     — no interaction; plain placeable block.
 *   <li>{@link Kind#SCRIPT}    — right-click runs a Rhino behavior script (generated by
 *       {@link LogicAgent}).
 *   <li>{@link Kind#WORKBENCH} — right-click opens a crafting-workbench GUI; the block entity
 *       processes the input ingredients → output over {@code ticks} ticks. The GUI lays out one
 *       slot per ingredient dynamically (1–9), so it need not be a square grid.
 * </ul>
 *
 * <p>The JSON schema returned by the model:
 * <pre>
 * {
 *   "interaction": "plain" | "script" | "workbench",
 *   "inputs": ["minecraft:iron_ingot", "minecraft:stick"],   // 1..9 ingredient ids
 *   "output": "minecraft:iron_sword",
 *   "output_count": 1,
 *   "fuel": "minecraft:coal",                                // optional; "" = no fuel
 *   "ticks": 100
 * }
 * </pre>
 * Fields other than {@code interaction} are only meaningful when {@code interaction == "workbench"}.
 */
public final class MachineAgent {

    /** The three possible interaction modes for a generated block. */
    public enum Kind { PLAIN, SCRIPT, WORKBENCH }

    /** Maximum number of ingredient cells a workbench recipe may have. */
    public static final int MAX_INPUTS = 9;

    /**
     * Result returned to {@link dev.conjure.gen.pipeline.BlockPipeline}.
     *
     * @param kind        interaction kind
     * @param inputs      ingredient item ids (1..{@value #MAX_INPUTS}); empty for non-workbench
     * @param output      output item registry id
     * @param outputCount items produced per craft (≥ 1)
     * @param fuel        optional fuel item id (blank = no fuel)
     * @param ticks       processing duration in ticks
     */
    public record Result(
            Kind kind,
            List<String> inputs,
            String output,
            int outputCount,
            String fuel,
            int ticks
    ) {
        /** Convenience constructor for non-workbench results. */
        public static Result plain()  { return new Result(Kind.PLAIN,  List.of(), "", 1, "", 0); }
        public static Result script() { return new Result(Kind.SCRIPT, List.of(), "", 1, "", 0); }
    }

    private static final String SYSTEM = """
            You decide how a Minecraft block generated by the Conjure mod behaves. Pick exactly one:
              "workbench" — the block PROCESSES, TRANSFORMS, smelts, bakes, brews, refines, grinds,
                            presses, or CRAFTS one thing into another, OR is named like a station,
                            workbench, table, machine, kiln, furnace, forge, mill, wheel, altar, or
                            similar workstation. Right-clicking opens a crafting GUI with a recipe.
              "script"    — the block does an instant magical/utility effect on right-click (heal,
                            teleport, sparkle, give an item) but does NOT process inputs over time.
              "plain"     — purely decorative or structural; nothing happens on right-click.

            Prefer "workbench" whenever the block could plausibly turn ingredients into a product.
            Examples: "clay kiln" → workbench, "glaze dipping station" → workbench, "ore crusher"
            → workbench, "wishing altar" → script, "glowing crystal block" → plain.

            For "workbench" also provide a recipe of REAL vanilla minecraft: items that exist:
              "inputs"       — 1 to 9 vanilla item ids consumed per craft (e.g.
                               ["minecraft:clay_ball"]); pick ingredients that fit the theme.
              "output"       — the vanilla item id produced.
              "output_count" — integer 1–64 produced per craft.
              "fuel"         — how the block is powered:
                                 ""      — no fuel needed.
                                 "any"   — burns ordinary fuel; use for a normal furnace/kiln/
                                           smelter/oven (the Minecraft convention: coal, charcoal,
                                           planks, blaze rods… all work).
                                 "<id>"  — requires EXACTLY this item, for a machine designed to run
                                           on a SPECIFIC custom fuel (e.g. "minecraft:redstone" for
                                           a powered machine, or a themed battery/crystal).
                               Prefer "any" for fire/heat stations; only name a specific item when
                               the machine is meant to consume that particular thing.
              "ticks"        — processing time in ticks (20 = 1 second; typical 60–200).

            Make the recipe the REASON to build this block: prefer thematic, on-flavor
            ingredients and a desirable output players would seek this station out for.

            Reply with ONLY a JSON object (no prose, no markdown fences):
            {
              "interaction": "plain" | "script" | "workbench",
              "inputs": ["<item id>", ...],
              "output": "<item id>",
              "output_count": 1,
              "fuel": "",
              "ticks": 100
            }
            For plain/script, all fields besides "interaction" may be omitted.
            """;

    /**
     * Focused prompt used to (re)derive a recipe once a block is known to be a workbench.
     * ponytail: the "make this the reason to craft the signature item" line is a prompt-only
     * nudge. Real per-item routing (custom item ids wired as this workbench's output) needs the
     * structured ModPlanner plan; upgrade there if the nudge proves too weak.
     */
    private static final String RECIPE_SYSTEM = """
            You design the crafting/processing recipe for a Minecraft "workbench" block from the
            Conjure mod. Given the block's description, choose what it consumes and produces using
            ONLY real vanilla minecraft: item ids that exist. Reply with ONLY a JSON object (no
            prose, no markdown fences):
            {
              "inputs": ["minecraft:<item>", ...],
              "output": "minecraft:<item>",
              "output_count": 1,
              "fuel": "",
              "ticks": 100
            }
            Use 1 to 9 ingredients and one output, thematically matching the block. Make this
            station the REASON players craft the mod's signature item: prefer on-flavor
            ingredients and a desirable output worth building the block for.
            "fuel": "" for no fuel, "any" for a normal fire-powered station (burns ordinary fuel),
            or a specific item id when the machine must run on that exact custom fuel.
            """;

    /**
     * Workstation words that force a {@link Kind#WORKBENCH} result regardless of what the model
     * says. Local models routinely misclassify obvious workstations as "plain"; this keyword
     * override is the cheap, reliable backstop (see plan / the pottery test case).
     */
    private static final String[] WORKBENCH_KEYWORDS = {
            "station", "workstation", "workbench", "bench", "kiln", "furnace", "smelter", "forge",
            "anvil", "wheel", "mill", "press", "loom", "altar", "brewing", "cauldron", "oven",
            "grinder", "crusher", "crafter", "fabricator", "assembler", "table", "processor",
            "refinery", "smithy", "kettle", "still", "vat", "smoker", "blaster", "infuser"
    };

    /** Whether {@code prompt} names a workstation that should always be a workbench. Pure function. */
    static boolean isWorkbenchKeyword(String prompt) {
        if (prompt == null) return false;
        String p = prompt.toLowerCase(java.util.Locale.ROOT);
        for (String kw : WORKBENCH_KEYWORDS) {
            if (p.contains(kw)) return true;
        }
        return false;
    }

    /**
     * Asks the text model what interaction kind best fits {@code prompt} and, for workbenches,
     * fills in a recipe. Falls back to sane defaults on a malformed reply rather than producing an
     * unusable recipe.
     *
     * @param prompt the original user-supplied block description
     * @return a {@link Result} with the chosen kind and optional recipe data
     * @throws Exception if the model call or JSON parse fails
     */
    public Result generate(String prompt) throws Exception {
        TextModelProvider provider = ProviderFactory.text();
        String userMsg = "Decide the interaction kind for this Minecraft block: " + prompt;
        String raw = provider.complete(SYSTEM, userMsg);

        JsonObject obj = JsonHelper.extractAndParse(raw, SYSTEM, provider, userMsg);

        String interaction = obj.has("interaction") ? obj.get("interaction").getAsString() : "plain";
        Kind kind = switch (interaction.toLowerCase().trim()) {
            case "workbench" -> Kind.WORKBENCH;
            case "script"    -> Kind.SCRIPT;
            default          -> Kind.PLAIN;
        };

        // Deterministic override: an obvious workstation is always a workbench, even if the model
        // (often a weak local model) called it plain/script.
        if (isWorkbenchKeyword(prompt)) kind = Kind.WORKBENCH;

        if (kind != Kind.WORKBENCH) {
            return kind == Kind.SCRIPT ? Result.script() : Result.plain();
        }

        // The classification reply may already carry a usable recipe; if not (e.g. the model said
        // "plain" and we overrode it), make a focused recipe-only call so we get a thematic recipe
        // instead of the bland default fallback.
        JsonObject recipeObj = hasUsableRecipe(obj) ? obj : focusedRecipe(provider, prompt);
        return parseRecipe(recipeObj);
    }

    /** Asks the model for a recipe only (no plain/script distractor); returns {@code {}} on failure. */
    private static JsonObject focusedRecipe(TextModelProvider provider, String prompt) {
        try {
            String userMsg = "Design a recipe for this workbench block: " + prompt;
            String raw = provider.complete(RECIPE_SYSTEM, userMsg);
            return JsonHelper.extractAndParse(raw, RECIPE_SYSTEM, provider, userMsg);
        } catch (Exception e) {
            return new JsonObject(); // fall through to parseRecipe's safe defaults
        }
    }

    /** True if {@code obj} has at least one non-blank input id and a non-blank output id. */
    private static boolean hasUsableRecipe(JsonObject obj) {
        boolean hasInput = false;
        if (obj.has("inputs") && obj.get("inputs").isJsonArray()) {
            for (JsonElement el : obj.getAsJsonArray("inputs")) {
                if (!el.isJsonNull() && !el.getAsString().trim().isBlank()) { hasInput = true; break; }
            }
        } else if (obj.has("recipe_input") && !obj.get("recipe_input").getAsString().trim().isBlank()) {
            hasInput = true;
        }
        boolean hasOutput = obj.has("output") && !obj.get("output").getAsString().trim().isBlank();
        return hasInput && hasOutput;
    }

    /** Parses a workbench recipe from {@code obj}, applying safe fallbacks for any missing field. */
    private static Result parseRecipe(JsonObject obj) {
        List<String> inputs = new ArrayList<>();
        if (obj.has("inputs") && obj.get("inputs").isJsonArray()) {
            JsonArray arr = obj.getAsJsonArray("inputs");
            for (int i = 0; i < arr.size() && inputs.size() < MAX_INPUTS; i++) {
                JsonElement el = arr.get(i);
                if (el.isJsonNull()) continue;
                String id = el.getAsString().trim();
                if (!id.isBlank()) inputs.add(id);
            }
        } else if (obj.has("recipe_input")) {
            String legacy = obj.get("recipe_input").getAsString().trim();
            if (!legacy.isBlank()) inputs.add(legacy);
        }
        if (inputs.isEmpty()) inputs.add("minecraft:cobblestone"); // safe fallback ingredient

        String output      = obj.has("output")       ? obj.get("output").getAsString().trim()       : "";
        int    outputCount = obj.has("output_count") ? obj.get("output_count").getAsInt()           : 1;
        String fuel        = obj.has("fuel")         ? obj.get("fuel").getAsString().trim()         : "";
        int    ticks       = obj.has("ticks")        ? obj.get("ticks").getAsInt()
                           : obj.has("recipe_ticks") ? obj.get("recipe_ticks").getAsInt()           : 100;

        if (output.isBlank()) output = "minecraft:stone"; // safe fallback
        outputCount = Math.max(1, Math.min(64, outputCount));
        ticks = Math.max(20, ticks);

        return new Result(Kind.WORKBENCH, inputs, output, outputCount, fuel, ticks);
    }

    public MachineAgent() {}

    /** ponytail: self-check for the pure keyword classifier — run with {@code java -ea}. */
    public static void main(String[] args) {
        assert isWorkbenchKeyword("glaze dipping station block") : "station → workbench";
        assert isWorkbenchKeyword("ceramic cutting wheel workstation") : "wheel/workstation → workbench";
        assert isWorkbenchKeyword("clay kiln") : "kiln → workbench";
        assert !isWorkbenchKeyword("glowing crystal block") : "decorative → not forced";
        assert !isWorkbenchKeyword("raw clay block") : "material → not forced";
        System.out.println("MachineAgent self-check passed.");
    }
}
